// react/coderwhy/day91_React全家桶实战_12/code/03_learn_component/src/03_组件开发嵌套关系/App.jsx
import React, { Component } from 'react'
import Header from './c-cpns/Header'
import Footer from './c-cpns/Footer'
import Main from './c-cpns/Main'

export class App extends Component {
  render() {
    return (
      <div className='app'>
        <Header/>
        <Main/>
        <Footer/>
      </div>
    )
  }
}

export default App

// vue/coderwhy/03_learn_component/src/01_组件的嵌套使用(重要)/App.vue
<template>
  <div class="app">
    <app-header></app-header>
    <app-content></app-content>
    <app-footer></app-footer>
  </div>
</template>

<script>
  import AppHeader from './components/AppHeader.vue'
  import AppContent from './components/AppContent.vue'
  import AppFooter from './components/AppFooter.vue'

  export default {
    components: {
      AppHeader,
      AppContent,
      AppFooter
    }
  }
</script>

<style scoped>
</style>
